<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AbsolverModTool.Core\AbsolverModTool.Core.csproj" />
    <ProjectReference Include="..\AbsolverViewer.Wpf\AbsolverViewer.Wpf.csproj" />
    <ProjectReference Include="..\AbsolverViewer.Paks\AbsolverViewer.Paks.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
